# Generated by Django 3.1.5 on 2021-04-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=25)),
                ('interest_rate', models.CharField(max_length=25)),
                ('tenure', models.CharField(max_length=20)),
            ],
        ),
    ]
